### ISSUE TITLE
RPC stubs on github

### ISSUE THREAD

**Issue by RyuMaster** [xaya/libxayagame#37]
Can we keep RPC generated stubs on github? On Windows, there is no easy way to generate those, i.e. library I have under msys can be only build without rpc-stubs support. So I need to switch to Linux, build there, then copy-past back on every clean update.

**Comment by domob1812** [comment]
I don't think we should.  But I'm happy to upload them every time something changes to some server (could even be public for everyone).

**Comment by RyuMaster** [comment]
Also then, is it possible to add some flag, that would ignore stub generation? Right now, I have to manually delete it from makefile, every time I git pull and build for windows

**Comment by domob1812** [comment]
The problem with premade stubs is that I don't know how correct they actually are - since they presumably depend in theory on your exact version of `jsonrpccpp`.  Thus this is all a hacky solution - so I don't want to make it too official.

Why can you build `jsonrpccpp` fine but not the stub generator in the first place?

**Comment by domob1812** [comment]
I believe that stub-generation on Windows works now, so we can close this.

**Comment by domob1812** [comment]
Also note that if we generate a source release (`make dist`), then the stubs will be included in it.  So this is/was mostly a problem for working from the repository directly.
