### ISSUE TITLE
Problems with CreateRpcServerConnector(...) in defaultmain.cpp

### ISSUE THREAD

**Issue by sjneph** [xaya/libxayagame#99]
I'm getting a couple of errors while compiling from the master branch.
Fedora 32
GCC 10.1.1

autogen.sh and configure seemed to work fine.

defaultmain.cpp:126:16: error: ‘class jsonrpc::HttpServer’ has no member named ‘BindLocalhost’
in function CreateRpcServerConnector.

The header on my system is the same as this one: https://github.com/cinemast/libjson-rpc-cpp/blob/master/src/jsonrpccpp/client/connectors/httpclient.h

The other error (due to -Werror=return-type) shown is also in CreateRpcServerConnector, and that complains that there is no return value in a non-void function (following the LOG statement).

**Comment by domob1812** [comment]
libxayagame needs a version of libjson-rpc-cpp that includes commit [`4f24acaf4c6737cd07d40a02edad0a56147e0713`](https://github.com/cinemast/libjson-rpc-cpp/commit/4f24acaf4c6737cd07d40a02edad0a56147e0713), due to an upstream fix we did.  For instance the current Debian stable packages don't include that yet.

This commit introduced the `BindLocalhost` function.  The other error about missing return value is just because the compiler doesn't go analysing deep enough (and figures out the `LOG(FATAL)` does not return) after the first, and it will be gone when you use the correct version of libjson-rpc-cpp.

**Comment by sjneph** [comment]
Thanks for the information.
